### ISSUE TITLE
Change Highlight Current Scope Keymap

### ISSUE THREAD

**Issue by slightfoot** [izhangzhihao/intellij-rainbow-brackets#61] opened 2018-05-16 12:06 UTC
I use `Ctrl` in IntelliJ all the time for quite a few operations. Having the scope flash different colours is very off putting when coding. It would be nice if we could remap the Key to something else. If you can get your plugin to register a Keymap in standard IntelliJ then we could change it to whatever suites the programmer.

For now, I am going to disable this feature.
Thank you for the awesome project. Very helpful when coding Flutter/Dart.

## Your Environment
* Plugin version: `5.7.1`
* IDE & Operating System version, comment your env as below(go to "About IntelliJ IDEA" -> click the "copy" icon):
```IntelliJ IDEA 2018.1.3 (Ultimate Edition)
Build #IU-181.4892.42, built on May 8, 2018
JRE: 1.8.0_152-release-1136-b38 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
```

**Comment by YiiGuxing** [comment] 2018-05-16 12:13
I have realized this problem, this feature will be implemented in the next version.

**Comment by dmitry-zaitsev** [comment] 2018-05-16 13:52
To add my few cents - the problem is even more crucial on Mac, where you have to press Cmd+Left or Cmd+Right instead of Home/End buttons on Windows.

**Comment by nvlad** [comment] 2018-05-16 14:17
may be add highlight delay? eq 0.5 second?

**Comment by izhangzhihao** [comment] 2018-05-16 14:22
Long press some key for 0.5 second? sounds good.

**Comment by nvlad** [comment] 2018-05-16 14:28
Yes. Сan make a configurable delay for highlighting.

**Comment by luispabon** [comment] 2018-05-18 10:25
Phew thank god it can be disabled. I don't think binding this feature to CTRL is a good idea since a great deal of keyboard shortcuts include CTRL. Every time you copy, paste, format, switch to the next tab, etc you get the current block flashing.

Maybe switch default binding to CTRL+SHIFT? These two keys should be together and actionable with the left pinky on any keyboard, and the right pinky on many others.

**Comment by izhangzhihao** [comment] 2018-05-26 04:29
I think is time to close this issue because version 5.8.X already for download.(#63)

**Closed as completed by izhangzhihao** 2018-05-26 04:29 UTC
Labels: feature request
