### ISSUE TITLE
[Rainbow variables] ALL colors in the IDE are broken even after uninstall

### ISSUE THREAD

**Issue by sla-te** [izhangzhihao/intellij-rainbow-brackets#2541] opened 2022-11-07 14:47 UTC
After updating to the newest version (freemium) ALL colors in the IDE are broken and it does not even fix it if i uninstall the plugin...

**Comment by sla-te** [comment] 2022-11-07 14:48
![image](https://user-images.githubusercontent.com/22568014/200339450-21b03f6a-832d-40d0-baf2-936b168db854.png)

**Comment by sla-te** [comment] 2022-11-07 14:57
And the best part is these settings appear to even get synced in the cloud, so now all IDEs are broken

**Comment by mikhailv** [comment] 2022-11-07 14:58
Same for me, spend some long minutes to understand reason of this
![image](https://user-images.githubusercontent.com/527152/200341013-069e9a48-ac20-4eed-b48a-78dc3bba6fe6.png)
As temporary workaround: Settings -> Editor -> Color Scheme , create duplicate of current theme with different name.
Uninstall of rainbow plugin or reinstall of color theme didn't fix colors, also reset of color theme to defaults didn't help.

**Comment by sla-te** [comment] 2022-11-07 15:01
`As temporary workaround: Settings -> Editor -> Color Scheme , create duplicate of current theme with different name.`
![image](https://user-images.githubusercontent.com/22568014/200342508-c664224e-6c02-4e0f-98cb-c5b24f46d6fc.png)
didnt fix it for me

**Comment by mikhailv** [comment] 2022-11-07 15:26
@sla-te then not sure what I did exactly to make this workaround to work. I tried to reinstall my current color theme and reset settings of color scheme to defaults. Maybe you need to repeat these steps to make it work. 
Also noticed that just clicking to Apply on settings window not enough, I my case I need to click OK to close settings window and apply scheme copy.

**Comment by sla-te** [comment] 2022-11-07 15:27
maybe interference with material theme ui - anyway im uninstalling it and reinstalling all my ides..

**Comment by mikhailv** [comment] 2022-11-07 15:42
Another solution - locate where custom color schemes stored in your system (for me it's `~/.config/JetBrains/IntelliJIdea2022.2/jba_config/colors`) and remove files (if you didn't changed colors) or try to edit these xml files.
There is line in xml
```
<property name="rainbow Default language">true</property> 
```
After removing it and restarting IDE all works fine.

**Comment by Stiropor** [comment] 2022-11-07 19:17
Whoever has this problem, disabling this option helped solving the problem for me:
![Screenshot 2022-11-07 at 20 10 32](https://user-images.githubusercontent.com/365876/200394457-4e5f3f9b-2fa7-43d9-9329-62b4f1f69f60.png)

This was pretty dumb idea to turn this on by default.

**Comment by bukajsytlos** [comment] 2022-11-07 19:46
@Stiropor thank you

**Comment by warcello** [comment] 2022-11-07 19:58
They wrote it in the change notes:

> Feature: enable rainbow variables by default(Config the colors here: Editor -> Scheme -> Language Defaults -> Semantic Highlighting)

You can disable it in the above Path.
However I agree that this was rather a bad idea.

**Comment by izhangzhihao** [comment] 2022-11-08 00:30
Hi, all disable this option here:
<img width="753" alt="image" src="https://user-images.githubusercontent.com/12044174/200444601-a5034c0e-6c3a-4415-93eb-978f6802a66b.png">

**Comment by izhangzhihao** [comment] 2022-11-08 03:51
In the next version, I made a notification:

<img width="383" alt="image" src="https://user-images.githubusercontent.com/12044174/200470979-3c507d0c-c838-4753-8435-a7cf879120a7.png">

**Comment by izhangzhihao** [comment] 2022-11-08 06:12
version 2022.3.3 is already in the marketplace.

**Closed as completed by izhangzhihao** 2022-11-08 06:12 UTC
Labels: question

**Comment by mikhailv** [comment] 2022-11-08 06:53
@izhangzhihao how is it possible that these "rainbow variables" works even after **rainbow-brackets** plugin unistalled?

**Comment by izhangzhihao** [comment] 2022-11-08 06:58
> @izhangzhihao how is it possible that these "rainbow variables" works even after **rainbow-brackets** plugin unistalled?

Good question, rainbow variables is actually the ["semantic highlighting"](https://www.youtube.com/watch?v=8WRH59PQ5Dk).

I'm considering better support and enhancements for this feature, like supporting more languages.

**Comment by michabbb** [comment] 2022-11-10 21:29
hi there, i had the same problem, so i was forced to disable the plugin, my last version phpstorm showed me:
![image](https://user-images.githubusercontent.com/3524595/201209530-2f093f5d-73b8-41f5-9193-88ed050582c9.png)

even I disabled the rainbow variables in the options, after a restart the variables were colored again, although the option in the setting was disabled.

**Comment by izhangzhihao** [comment] 2022-11-11 00:32
> hi there, i had the same problem, so i was forced to disable the plugin, my last version phpstorm showed me: ![image](https://user-images.githubusercontent.com/3524595/201209530-2f093f5d-73b8-41f5-9193-88ed050582c9.png)
> 
> even I disabled the rainbow variables in the options, after a restart the variables were colored again, although the option in the setting was disabled.

Hi, you must disable the option here: 

<img width="422" alt="image" src="https://user-images.githubusercontent.com/12044174/201234399-977aec21-c020-4de5-a176-eb12ffaf8cf3.png">

And this will disable automatically:

<img width="873" alt="image" src="https://user-images.githubusercontent.com/12044174/201234476-d2a2d979-4ae3-4ad4-b7e8-af65adb1c23c.png">

And all things will revert back.

**Comment by izhangzhihao** [comment] 2022-11-11 00:37
Or click "Not now" here:

<img width="386" alt="image" src="https://user-images.githubusercontent.com/12044174/201235154-5953ed3e-3bd9-46db-bfa5-92f04dbe70d3.png">

**Comment by izhangzhihao** [comment] 2022-11-11 00:51
Hi, sorry for the mistake, please use this one.

**Comment by michabbb** [comment] 2022-11-11 20:22
i installed the version from your link, and so far so good... looks like I have my nice brackets but variables stay untouched 😏

**Comment by caifelixpenrose** [comment] 2022-11-15 09:42
Just ran into this myself. I should have read that popup more clearly my bad.
The issue really is that Semantic Highlighting gets turned on, and even after you disable that setting, then restart php storm the setting is turned back on.

I had not realised these two settings were the same, but yes after disabling in the plugin setting, this is no longer a problem. Thanks
